# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AbhishekFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'SwiftKeychainWrapper'

  target 'AbhishekFrameworkTests' do
    # Pods for testing
  end

end
